const ROSTER = [
  { idx: 59, name: 'Up 2 Yim', handle: '@Adyim_Channel', channelIdMode: false, verdict: 'CUT', spend: 2000.0, game: 'PUBG Mobile' },
  { idx: 61, name: 'LookBaz Channel', handle: '@LookBazChannel', channelIdMode: false, verdict: 'WATCH', spend: 30927.84, game: 'PUBG Mobile' },
  { idx: 16, name: 'K2J', handle: '@k2j999zx', channelIdMode: false, verdict: 'KEEP', spend: 45000.0, game: 'Free Fire' },
  { idx: 62, name: 'BobInRoam', handle: '@BobInRoam', channelIdMode: false, verdict: 'KEEP', spend: 3000, game: 'Mobile Legends BANG BANG' },
  { idx: 35, name: 'Cindry 999', handle: '@cindrywrld.999', channelIdMode: false, verdict: 'KEEP', spend: 50000.0, game: 'Arena of Valor (ROV) + Mobile Legends BANG BANG' },
  { idx: 80, name: 'Mablle.a', handle: '@mabelle.a', channelIdMode: false, verdict: 'WATCH', spend: 7000.0, game: 'Genshin Impact , Honkai Star Rail , Zenless Zone Zero (ZZZ)' },
  { idx: 98, name: 'Full Sense (Porzanaruk)', handle: '@PORZANARUKK', channelIdMode: false, verdict: 'KEEP', spend: 25000.0, game: 'Valorant' },
  { idx: 56, name: 'Lakoi Play', handle: '@LakoiPlay', channelIdMode: false, verdict: 'KEEP', spend: 50000.0, game: 'Genshin Impact , Honkai Star Rail , Zenless Zone Zero (ZZZ)' },
  { idx: 22, name: 'NCZ', handle: '@NCZCH', channelIdMode: false, verdict: 'CUT', spend: 4500.0, game: 'Ragnarok PC' },
  { idx: 38, name: 'PzFx', handle: '@PzFxOfficial', channelIdMode: false, verdict: 'WATCH', spend: 10000.0, game: 'Valorant' },
  { idx: 50, name: 'Aleister Everyday', handle: '@AleisterEveryday', channelIdMode: false, verdict: 'WATCH', spend: 35000.0, game: 'Arena of Valor (ROV)' },
  { idx: 7, name: 'AMPVERSE (Pjy Gamer)', handle: '@PJYGamer', channelIdMode: false, verdict: 'KEEP', spend: 50000.0, game: 'Mobile Legends BANG BANG' },
  { idx: 76, name: 'Chaly26z', handle: '@Chaly26z', channelIdMode: false, verdict: 'CUT', spend: 3000.0, game: 'Arena Break OUT Mobile' },
  { idx: 13, name: 'HBX', handle: '@HBXHybridX', channelIdMode: false, verdict: 'KEEP', spend: 36000.0, game: 'Mobile Legends BANG BANG' },
  { idx: 81, name: 'MOBYDICK', handle: '@MobyDickChannel', channelIdMode: false, verdict: 'WATCH', spend: 30000.0, game: 'IDENTITY V' },
  { idx: 8, name: 'Full Sense (JohnOlsen)', handle: '@johnolsen_official3854', channelIdMode: false, verdict: 'KEEP', spend: 20000.0, game: 'Valorant' },
  { idx: 83, name: 'Just Jay', handle: '@justjay9672', channelIdMode: false, verdict: 'WATCH', spend: 15000.0, game: 'One Punch Man or Manga Game' },
  { idx: 23, name: 'LadySorun', handle: '@LadySorunz', channelIdMode: false, verdict: 'CUT', spend: 7000.0, game: 'IDENTITY V' },
  { idx: 42, name: 'ทีโอเค🇹🇭 FF', handle: '@TOKFF_TH', channelIdMode: false, verdict: 'WATCH', spend: 5500.0, game: 'Free Fire' },
  { idx: 6, name: 'AMPVERSE (CGGG Detbuu)', handle: '@cggg_detbuu', channelIdMode: false, verdict: 'KEEP', spend: 50000.0, game: 'Free Fire' },
  { idx: 43, name: 'ดาวยิ้ม', handle: '@daoyimstudio', channelIdMode: false, verdict: 'KEEP', spend: 6600, game: 'Arena of Valor (ROV)' },
  { idx: 26, name: 'BrOwnii3z', handle: '@BrOwnii3z', channelIdMode: false, verdict: 'KEEP', spend: 22000.0, game: 'Valorant' },
  { idx: 3, name: 'AMPVERSE (PojzPlaza)', handle: '@PPZ321', channelIdMode: false, verdict: 'KEEP', spend: 120000.0, game: 'Free Fire' },
  { idx: 45, name: 'ตำรากอลิล่า', handle: '@NICK465', channelIdMode: false, verdict: 'CUT', spend: 1600, game: 'Genshin Impact' },
  { idx: 1, name: 'AMPVERSE (Bboss)', handle: '@BossNatthapat', channelIdMode: false, verdict: 'KEEP', spend: 120000.0, game: 'Mobile Legends BANG BANG' },
  { idx: 25, name: 'Rydens CH', handle: '@RydensCH', channelIdMode: false, verdict: 'CUT', spend: 7000.0, game: 'dragon traveler + Tree of Savior M' },
  { idx: 64, name: 'GOD USOPP', handle: '@godusopp1986', channelIdMode: false, verdict: 'WATCH', spend: 15450.0, game: 'Arena of Valor (ROV)' },
  { idx: 57, name: 'AD-AOF TV', handle: '@ADAOFTV', channelIdMode: false, verdict: 'WATCH', spend: 40000.0, game: 'Wuthering Waves +  Seven Knights +  Arknight Enfield' },
  { idx: 79, name: 'ManueL', handle: '@manuel6248', channelIdMode: false, verdict: 'WATCH', spend: 12000.0, game: 'Arena of Valor (ROV)' },
  { idx: 14, name: 'SiNEz', handle: '@SiNEz.', channelIdMode: false, verdict: 'WATCH', spend: 15000.0, game: 'Arena of Valor (ROV)' },
  { idx: 89, name: '4EM', handle: '@4emChannel', channelIdMode: false, verdict: 'WATCH', spend: 8000.0, game: 'Mobile Legends BANG BANG' },
  { idx: 70, name: 'Bennyy Channel', handle: '@bennyych', channelIdMode: false, verdict: 'WATCH', spend: 8000.0, game: 'PUBG Mobile' },
  { idx: 21, name: 'White Sky Ch.', handle: '@WhiteskyCh.6', channelIdMode: false, verdict: 'CUT', spend: 4000, game: 'Genshin Impact' },
  { idx: 66, name: '382ICE', handle: '@382ICE', channelIdMode: false, verdict: 'WATCH', spend: 12000, game: 'Arena Break OUT Mobile' },
  { idx: 15, name: 'ARASTi', handle: '@arasti4603', channelIdMode: false, verdict: 'WATCH', spend: 23000.0, game: 'Arena of Valor (ROV)' },
  { idx: 87, name: 'Nakama Channel', handle: '@NakamaChannel', channelIdMode: false, verdict: 'CUT', spend: 6000.0, game: 'TFT (Teamfight Tactics)' },
  { idx: 29, name: 'Angel Deathgame', handle: '@ANGELDEATHGAME', channelIdMode: false, verdict: 'WATCH', spend: 9793.81, game: 'One Punch Man or Manga Game' },
  { idx: 82, name: 'TakoyakiCh', handle: '@TakoyakiChYT', channelIdMode: false, verdict: 'WATCH', spend: 25000.0, game: 'Ragnarok PC Class 4 + Landverse + POE' },
  { idx: 84, name: 'DevilReview', handle: '@DevilReview', channelIdMode: false, verdict: 'WATCH', spend: 12000.0, game: 'Ragnarok Mobile' },
  { idx: 51, name: 'REMULESSS', handle: '@Remulesss', channelIdMode: false, verdict: 'WATCH', spend: 25000.0, game: 'Honkai Star Rail , Zenless Zone Zero (ZZZ)' },
  { idx: 96, name: 'Justinated', handle: '@Justinated', channelIdMode: false, verdict: 'WATCH', spend: 15000.0, game: 'Genshin Impact + Honkai Star Rail + Wuthering Waves' },
  { idx: 46, name: 'KKZ x2', handle: '@kkzx2658', channelIdMode: false, verdict: 'CUT', spend: 7500.0, game: 'PUBG Mobile' },
  { idx: 40, name: 'Oreiei', handle: '@Oreiei', channelIdMode: false, verdict: 'CUT', spend: 2500.0, game: 'Honkai Star Rail' },
  { idx: 44, name: 'ChaSam', handle: '@ChaSam42', channelIdMode: false, verdict: 'WATCH', spend: 8340, game: 'Genshin Impact , Honkai Star Rail , Zenless Zone Zero (ZZZ) + Wuthering Waves' },
  { idx: 78, name: 'RrrrMoss', handle: '@RrrrMoss', channelIdMode: false, verdict: 'WATCH', spend: 13000.0, game: 'Mobile Legends BANG BANG' },
  { idx: 19, name: 'EDM (WakeUp Ruj)', handle: '@wakeupruj', channelIdMode: false, verdict: 'KEEP', spend: 33333.33, game: 'Valorant' },
  { idx: 30, name: 'E ORYAI', handle: '@EORYAI', channelIdMode: false, verdict: 'WATCH', spend: 10000.0, game: 'Free Fire' },
  { idx: 73, name: 'Simuraz', handle: '@SimurazCH', channelIdMode: false, verdict: 'CUT', spend: 7200, game: 'Path of Exile 2' },
  { idx: 34, name: 'God cat', handle: '@GODCATz', channelIdMode: false, verdict: 'WATCH', spend: 9600, game: 'Arena Break OUT Mobile' },
  { idx: 60, name: 'Kenshin X.', handle: '@KenshinXMLBB', channelIdMode: false, verdict: 'CUT', spend: 1500.0, game: 'Mobile Legends BANG BANG' },
  { idx: 75, name: 'Rycub', handle: '@Rycub', channelIdMode: false, verdict: 'CUT', spend: 4500.0, game: 'Mobile Legends BANG BANG' },
  { idx: 72, name: 'PixrPulse', handle: '@PixrPulse', channelIdMode: false, verdict: 'CUT', spend: 3000.0, game: 'Honkai Star Rail' },
  { idx: 12, name: 'AbGamingZ', handle: '@AbGamingZ', channelIdMode: false, verdict: 'KEEP', spend: 15000.0, game: 'Arena of Valor (ROV) + Mobile Legends BANG BANG' },
  { idx: 36, name: 'HookHuukGaming', handle: '@HookHuukGaming', channelIdMode: false, verdict: 'WATCH', spend: 6000.0, game: 'Genshin Impact , Honkai Star Rail , Zenless Zone Zero (ZZZ) , Ragnarok PC + Wuthering Waves +  Seven Knights + Arknight Enfield' },
  { idx: 52, name: 'เพราะเป็น Jungle จึงเจ็บปวด', handle: '@loljunglestory', channelIdMode: false, verdict: 'WATCH', spend: 10000.0, game: 'LOL PC (League of Legends)' },
  { idx: 53, name: 'Zed Cat', handle: '@ZedCat', channelIdMode: false, verdict: 'WATCH', spend: 9000.0, game: 'LOL PC (League of Legends)' },
  { idx: 71, name: 'KanOmPang', handle: '@kanompang7669', channelIdMode: false, verdict: 'WATCH', spend: 5000.0, game: 'Honkai Star Rail , Zenless Zone Zero (ZZZ)' },
  { idx: 41, name: 'SarA9', handle: '@SarA9Official', channelIdMode: false, verdict: 'WATCH', spend: 6000.0, game: 'Mobile Legends BANG BANG' },
  { idx: 74, name: 'KR Muffinz', handle: '@KRMuffinz49', channelIdMode: false, verdict: 'KEEP', spend: 20000.0, game: 'Mobile Legends BANG BANG' },
  { idx: 85, name: 'Jz Oracle', handle: '@JzOracleChannel', channelIdMode: false, verdict: 'KEEP', spend: 18000.0, game: 'RoBlox' },
  { idx: 48, name: 'SOMZ SU', handle: '@somzsu', channelIdMode: false, verdict: 'WATCH', spend: 24000, game: 'PUBG Mobile' },
  { idx: 47, name: 'วาว่า', handle: '@WAWAGGEZ', channelIdMode: false, verdict: 'KEEP', spend: 15000.0, game: 'Mobile Legends BANG BANG' },
  { idx: 31, name: 'Pattun Chuen', handle: '@PattunChuen', channelIdMode: false, verdict: 'CUT', spend: 2400, game: 'Honkai Star Rail' },
  { idx: 27, name: 'Doyser', handle: '@Doyser', channelIdMode: false, verdict: 'KEEP', spend: 90000.0, game: 'Mobile Legends BANG BANG' },
  { idx: 39, name: 'BIGCOKE NO.1', handle: '@bigcokeno1', channelIdMode: false, verdict: 'CUT', spend: 3500.0, game: 'เกมใหม่ๆ PC & MOBILE' },
  { idx: 55, name: 'เกนชินไม่ใช่เกมส์มือถือ', handle: '@Genshinmaichaigamemurtur', channelIdMode: false, verdict: 'WATCH', spend: 6000.0, game: 'Genshin Impact' },
  { idx: 37, name: 'SpaceUnicorn', handle: '@SpaceUnicornHQ', channelIdMode: false, verdict: 'CUT', spend: 2400.0, game: 'Zenless Zone Zero (ZZZ)' },
  { idx: 17, name: 'Ron B', handle: '@RONB_999', channelIdMode: false, verdict: 'WATCH', spend: 35000.0, game: 'RoBlox' },
  { idx: 2, name: 'AMPVERSE (Nontakan Ns.)', handle: 'UCadvHR_ymmdouo3Sgb7Uf_w', channelIdMode: true, verdict: 'KEEP', spend: 107000.0, game: 'Arena of Valor (ROV) + Mobile Legends BANG BANG' },
  { idx: 94, name: 'MeMarkz Channel / MeMarkz', handle: '@MeMarkz.k', channelIdMode: false, verdict: 'KEEP', spend: 17000.0, game: 'MLBB (Mobile Legends Bang Bang)' },
  { idx: 67, name: 'Double K', handle: '@oDoubleKo', channelIdMode: false, verdict: 'KEEP', spend: 35000.0, game: 'Arena of Valor (ROV) + Mobile Legends BANG BANG' },
  { idx: 9, name: 'Full Sense (SuperBusS)', handle: '@superbussofficial8705', channelIdMode: false, verdict: 'KEEP', spend: 40000.0, game: 'Valorant' },
  { idx: 58, name: 'POC Glass', handle: '@POCGlass.official', channelIdMode: false, verdict: 'CUT', spend: 3000.0, game: 'Delta Force ( Mobile)' },
  { idx: 63, name: 'Ploy Mini', handle: '@ployminichannel', channelIdMode: false, verdict: 'WATCH', spend: 25000.0, game: 'PUBG Mobile' },
  { idx: 77, name: 'Tticc channel', handle: '@Tticcchannel', channelIdMode: false, verdict: 'WATCH', spend: 12000.0, game: 'Ragnarok Mobile' },
  { idx: 86, name: 'AzZing', handle: '@AzZing2KD', channelIdMode: false, verdict: 'WATCH', spend: 10000.0, game: 'Ragnarok PC' },
  { idx: 5, name: 'AMPVERSE (Bacon ReMix)', handle: '@BaconRemix', channelIdMode: false, verdict: 'KEEP', spend: 40000.0, game: 'Mobile Legends BANG BANG' },
  { idx: 28, name: 'Bee Chilling', handle: '@beechilling', channelIdMode: false, verdict: 'CUT', spend: 5500.0, game: 'TFT (Teamfight Tactics)' },
  { idx: 91, name: 'สึสึ', handle: '@tsutsugaming', channelIdMode: false, verdict: 'WATCH', spend: 45000.0, game: '' },
  { idx: 95, name: 'Fayyee Online', handle: '@FayyeeOnline', channelIdMode: false, verdict: 'WATCH', spend: 8500, game: 'LOL PC (League of Legends)' },
  { idx: 24, name: 'StopsGame', handle: '@เอ็มคุง', channelIdMode: false, verdict: 'CUT', spend: 5200.0, game: 'Ragnarok PC' },
  { idx: 54, name: 'SpyCap', handle: '@SpyCapy', channelIdMode: false, verdict: 'WATCH', spend: 10000.0, game: 'เกมค่าย  HoYoverse' },
  { idx: 4, name: 'AMPVERSE (Wanoiz)', handle: '@Wanoiz', channelIdMode: false, verdict: 'KEEP', spend: 65625.0, game: 'Arena of Valor (ROV)' }
];